# Generated by Django 5.0.6 on 2024-06-09 00:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('direccion', models.CharField(max_length=50, verbose_name='Dirección')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('portada', models.ImageField(blank=True, null=True, upload_to='portadas/', verbose_name='Portada')),
                ('titulo', models.CharField(max_length=50, verbose_name='Título')),
                ('autor', models.CharField(max_length=50, verbose_name='Autor')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)], verbose_name='Stock')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factura', models.CharField(max_length=10, unique=True, verbose_name='Factura')),
                ('fecha_venta', models.DateField(auto_now_add=True, verbose_name='Fecha venta')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto total')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='laBiblioteca.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='VentaLibro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)], verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laBiblioteca.libro')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laBiblioteca.venta')),
            ],
        ),
        migrations.AddField(
            model_name='venta',
            name='libros',
            field=models.ManyToManyField(through='laBiblioteca.VentaLibro', to='laBiblioteca.libro'),
        ),
    ]
